spring:
  application:
    name: settlement-service
  datasource:
    url: jdbc:mysql://${DB_HOST}:${MYSQL_CONTAINER_PORT:3306}/${DB_NAME}?createDatabaseIfNotExist=true&autoReconnect=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:F1mQ3r8+L4YgD9qQbq1F9i3mGQm1m2X7s8P0n4X6k2Q=}
  expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}

admin:
  seed-username: ${ADMIN_USERNAME:admin}
  seed-password: ${ADMIN_PASSWORD:password}

DB_HOST: 127.0.0.1
DB_USERNAME: settlement
DB_PASSWORD: settlement
DB_NAME: settlement_service
MYSQL_CONTAINER_PORT: 3306