spring:
  application:
    name: settlement-service
  datasource:
    url: jdbc:mysql://${DB_HOST}:${MYSQL_CONTAINER_PORT:3306}/${DB_NAME}?createDatabaseIfNotExist=true&autoReconnect=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

DB_HOST: 127.0.0.1
DB_USERNAME: settlement
DB_PASSWORD: settlement
DB_NAME: settlement_service
MYSQL_CONTAINER_PORT: 3306